export const RESET_ALL = 'RESET_ALL';

export const INTERFACE_REQUEST = 'INTERFACE_REQUEST';
export const INTERFACE_COMPLETE = 'INTERFACE_COMPLETE';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

export const FETCH_PATIENT_REQUEST = 'FETCH_PATIENT_REQUEST';
export const FETCH_PATIENT_SUCCESS = 'FETCH_PATIENT_SUCCESS';
export const FETCH_PATIENT_ERROR = 'FETCH_PATIENT_ERROR';

export const FETCH_PATIENTS_REQUEST = 'FETCH_PATIENTS_REQUEST';
export const FETCH_PATIENTS_SUCCESS = 'FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENTS_ERROR = 'FETCH_PATIENTS_ERROR';
export const FETCH_PATIENTS_RESET = 'FETCH_PATIENTS_RESET';

export const UPDATE_PATIENT_REQUEST = 'SEARCH_PATIENT_REQUEST';
export const UPDATE_PATIENT_SUCCESS = 'SEARCH_PATIENT_SUCCESS';
export const UPDATE_PATIENT_ERROR = 'SEARCH_PATIENT_ERROR';
